# PREFIX FOLDING RULES:
# startup-* → startup (except specific technical terms)
# founder-* → founder (except specific technical terms)
# ai-* → ai (except technical keepers: ai-agents, llm, prompt-injection, harm-limiting, ai-observability, ai-inference-caching)

# Example applications of prefix rules:
# startup-strategy → startup
# startup-lessons → startup
# founder-led → founder
# founder-mindset → founder
# ai-tools → ai
# ai-development → ai

# EXPLICIT MAPPINGS (overrides and non-prefix cases):


GraphQL: graphql
GraphQL-federation: graphql-federation
MCP: mcp
MCP-server: mcp-server
agent-mode: agent-mode
agents: ai-agents
ai-acceleration: ai
ai-adoption: ai
ai-agent-competition: ai
ai-agents: ai-agents
ai-and-careers: ai
ai-assisted-development: ai
ai-autonomy: ai
ai-blackmail: ai
ai-boom: ai
ai-bubble: ai
ai-code-percentage: ai
ai-collaboration: ai
ai-data-patterns: ai
ai-detection: ai
ai-development: ai
ai-development-tools: ai
ai-discovery: ai
ai-economics: ai
ai-ecosystems: ai
ai-employees: ai
ai-empowerment: ai
ai-engineer: ai
ai-first-strategy: ai
ai-gaming-tests: ai
ai-generated-libraries: ai
ai-governance: ai
ai-impact: ai
ai-incentives: ai
ai-infrastructure: ai
ai-integration: ai
ai-integrations: ai
ai-investment: ai
ai-investment-trends: ai
ai-investment-wave: ai
ai-languages: ai
ai-limitations: ai
ai-mandate: ai
ai-misconceptions: ai
ai-news-analysis: ai
ai-productivity: ai
ai-quality-standards: ai
ai-research: ai
ai-roleplay: ai
ai-search-engine: ai
ai-startups: ai
ai-testing: ai
ai-tool-monetization: ai
ai-tooling: ai
ai-tools: ai
ai-transformation: ai
ai-trends: ai
ai-trust-issues: ai
ai-valuations: ai
ai-verification: ai
ai-workflows: ai
ai-wrappers: ai
api sprawl: api-sprawl
api-consumers: api-consumers
api-design: api-design
api-ecosystem: api-ecosystem
api-expert: api-expert
api-gateway: api-gateway
api-mandate: api-mandate
apollo-connectors: apollo-connectors
apollo-federation: graphql-federation
apollo-graphql: apollo-graphql
authentication: authentication
authenticity: authenticity
authorization: authorization
backend for frontend: bff-pattern
backend-for-frontend: bff-pattern
benchmarking: benchmarking
benchmarks: benchmarks
bff: bff-pattern
cache-warmer: cache-warmer
cache-warming: cache-warming
cdn: cdn
ciroos: ciroos
compose error: composition-errors
composite-schema: composite-schema
composition: composition
composition error: composition-errors
composition failures: composition-errors
composition-checks: composition-checks
computer-science: computer-science
connector-approach: connector-approach
contract-testing: contract-testing
contracts: contracts
conway's law: conways-law
conways law: conways-law
cosmo: cosmo
cosmo-router: cosmo-router
customer-abandonment: startup
customer-advocacy: startup
customer-behavior: startup
customer-communication: startup
customer-development: startup
customer-education: startup
customer-empathy: startup
customer-excitement: startup
customer-expectations: startup
customer-experience: startup
customer-first: startup
customer-listening: startup
customer-logos: startup
customer-needs: startup
customer-onboarding: startup
customer-partnerships: startup
customer-patterns: startup
customer-proximity: startup
customer-research: startup
customer-stories: startup
customer-success: startup
customer-support: startup
customer-validation: startup
data-dependencies: data-dependencies
data-loading: data-loading
database: database
datadog: datadog
diffs (schema context): schema-diffs   # only if clearly schema-related
dream-query: dream-query
dream-query-workflow: dream-query-workflow
entity fetch: entity-fetching
entity fetching: entity-fetching
entity resolution (if used to mean fetching): entity-fetching
federation: federation
federation-descriptions: federation-descriptions
first-startup: startup
founder-accountability: founder
founder-advantage: founder
founder-background: founder
founder-drive: founder
founder-empathy: founder
founder-led: founder
founder-mindset: founder
founder-mode: founder
founder-pressure: founder
founder-quality: founder
founder-stress: founder
founder-transparency: founder
founder-trust: founder
gRPC: grpc
github-copilot: github-copilot
github-for-apis: github-for-apis
go: go
go-to-market: go-to-market
golang: go
governance: governance
graph-composition: graph-composition
graphql: graphql
graphql-api: graphql-api
graphql-engine: graphql-engine
graphql-federation: graphql-federation
graphql-go-tools: graphql-go-tools
graphql-guild: graphql-guild
graphql-operations: graphql-operations
graphql-spec: graphql-spec
graphql-validation: graphql-validation
grpc: grpc
harm-limiting: harm-limiting
hypermedia-apis: hypermedia-apis
implicit-behavior: implicit-behavior
indecision: indecision
internal-apis: internal-apis
json-schema: json-schema
kafka: kafka
kansas-city: kansas-city
kubernetes: kubernetes
llm: llm
llm-agents: llm-agents
llm-behavior: llm
llm-code-generation: llm
llm-communication: llm
llm-constraints: llm
llm-context: llm
llm-education: llm
llm-optimization: llm
llm-safety: harm-limiting
llm-tools: llm
macro-benchmarks: macro-benchmarks
market-analysis: startup
market-challenger: startup
market-concentration: startup
market-consolidation: startup
market-differentiation: startup
market-dominance: startup
market-dynamics: startup
market-entry: startup
market-knowledge: startup
market-maturity: startup
market-oversaturation: startup
market-positioning: startup
market-saturation: startup
market-signals: startup
market-size: startup
market-timing: startup
mcp: mcp
mcp-availability: mcp
mcp-benefits: mcp
mcp-challenges: mcp
mcp-configuration: mcp
mcp-demo: mcp
mcp-gateway: mcp-gateway
mcp-implementation: mcp
mcp-inspector: mcp-inspector
mcp-integration: mcp
mcp-marketplace: mcp
mcp-registry: mcp-registry
mcp-security: mcp
mcp-tools: mcp-tools
mcp-validation: mcp
metadata: metadata
micro-benchmarks: micro-benchmarks
microservices: microservices
microservices-architecture: microservices-architecture
model-context-protocol: mcp
monolith: monolith
monolith migration to federation: monolith-to-federation
monolith to federation: monolith-to-federation
monolith→federation: monolith-to-federation
mysql: mysql
observability: observability
open-api: open-api
open-source-alternatives: open-source
open-source-business: open-source
open-source-commitment: open-source
open-source-community: open-source
open-source-funnel: open-source
open-source-game-theory: open-source
open-source-maintenance: open-source
open-source-monetization: open-source
openapi: openapi
plugin-system: plugin-system
postgres: postgres
pricing: pricing
pricing-strategy: pricing-strategy
principal-architect: principal-architect
principled-graphql: principled-graphql
product-adoption: startup
product-complexity: startup
product-criticism: startup
product-demo: startup
product-development: startup
product-direction: startup
product-evolution: startup
product-identity: startup
product-iteration: startup
product-market-fit: startup
product-marketing: startup
product-pivot: startup
product-pivots: startup
product-roadmaps: startup
product-success: startup
product-vision: startup
prompt-injection: prompt-injection
python: python
query-planning: query-planning
real-api-integration: real-api-integration
resilience: resilience
rest: rest
rest-apis: rest-apis
rest-connectors: rest-connectors
rich-metadata: rich-metadata
router-configuration: router-configuration
rust: rust
schema diff: schema-diffs
schema diffs: schema-diffs
schema-checks: schema-checks
schema-evolution: schema-evolution
schema-exploration: schema-exploration
schema-first: schema-first
schema-registry: schema-registry
schema-validation: schema-validation
small-startup-strategy: startup
social-proof: social-proof
specifications: specifications
startup-advantages: startup
startup-advice: startup
startup-competition: startup
startup-creativity: startup
startup-credits: startup
startup-culture: startup
startup-defensibility: startup
startup-ecosystem: startup
startup-evaluation: startup
startup-feedback: startup
startup-funding: startup
startup-growth: startup
startup-humility: startup
startup-ideas: startup
startup-journey: startup
startup-leadership: startup
startup-life: startup
startup-luck: startup
startup-maturity: startup
startup-mechanics: startup
startup-mistakes: startup
startup-moats: startup
startup-operations: startup
startup-philosophy: startup
startup-reliability: startup
startup-retreat: startup
startup-revenue: startup
startup-security: startup
startup-success: startup
startup-trends: startup
startup-viability: startup
startup-vision: startup
startup-waves: startup
subgraph-libraries: subgraph-libraries
supergraph: supergraph
telemetry: telemetry
trusted-documents: trusted-documents
typescript: typescript
universal-data-graph: universal-data-graph
usage-based-pricing: usage-based-pricing
venture-capital: venture-capital
vitess: vitess
zero-incidents: zero-incidents


# --- Normalization & variant merges ---
open-api: openapi
graphql api: graphql
graphql federation: graphql-federation
websockets: websocket
circuit-breaker: circuit-breakers
k8s: kubernetes
rest apis: rest-apis
schema stitching: schema-stitching
entity-resolution: entity-fetching
entity resolution: entity-fetching

# --- Prefer a single canonical form ---
benchmarks: benchmarking
cache-warmer: cache-warming
graph-composition: composition
llm-agents: ai-agents
query planner: query-planning
planner hops: query-planning

# --- MCP folds (keep mcp-gateway distinct) ---
mcp-server: mcp
mcp-inspector: mcp
mcp-registry: mcp
mcp-tools: mcp
open federation: open-federation
openfed: open-federation

# --- Business/meta roll-ups (or delete if you prefer a purely technical KB) ---
go-to-market: startup
pricing: startup
pricing-strategy: startup
usage-based-pricing: startup
venture-capital: startup
principal-architect: startup
kansas-city: startup
api-mandate: startup
github-for-apis: startup

# --- AI/productivity odds & ends ---
github-copilot: ai

# --- Previously noted synonyms for composition errors & diffs ---
compose error: composition-errors
composition failures: composition-errors
composition error: composition-errors
schema diff: schema-diffs
schema diffs: schema-diffs
diffs (schema context): schema-diffs
